[toolchain]
channel = "1.77.0"
components = ["rust-src"]
targets = [ 
	"aarch64-apple-darwin",
	"aarch64-apple-ios",
	"aarch64-apple-ios-sim",
	"x86_64-apple-darwin",
	"x86_64-apple-darwin",
	"aarch64-linux-android",
	"armv7-linux-androideabi",
	"i686-linux-android",
	"i686-linux-android",
]
