[package]
name = "e2ee-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
e2ee = { path = "../e2ee" }
clap = { version = "4.5.7", features = ["derive"] }

